name: Build S-Inject

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [Win32, x64]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake (${{ matrix.platform }})
      run: cmake -B ${{github.workspace}}/build -A ${{ matrix.platform }} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build (${{ matrix.platform }})
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Upload Artifacts (${{ matrix.platform }})
      uses: actions/upload-artifact@v4
      with:
        name: S-Inject-${{ matrix.platform }}-${{ env.BUILD_TYPE }}
        path: ${{github.workspace}}/build/${{env.BUILD_TYPE}}/S-Inject.exe
        if-no-files-found: error
